language: android
android:
  components:
    - build-tools-22.0.1
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

script:
  - ./gradlew assemble
  - ./gradlew test

